name: Send Push Messages To All Users

on:
  schedule:
    - cron: "0 17 * * 5" #Every Monday 1915

jobs:
  run-curl-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sending Push Notifications
        run: |
          curl --location --request POST 'https://w1ofof2wuh.execute-api.eu-central-1.amazonaws.com/dev/sendpushmessagetoall?title=Handelsweek%20afgesloten&body=Alle%20transacties%20worden%20nu%20verwerkt%20en%20zijn%20maandag%20om%2019%3A00%20uur%20zichtbaar%20in%20jouw%20app.' \
          --header 'accept: application/json'
