name: Send Push Messages To All Users

on:
  schedule:
    - cron: '0 18 * * 5' #Every Monday 1915

jobs:
  run-curl-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sending Push Notifications
        run: |
          curl --location 'https://w1ofof2wuh.execute-api.eu-central-1.amazonaws.com/dev/sendpushmessagetoall?title=Handelsweek%20afgesloten&body=Alle%20transacties%20worden%20nu%20tegen%20de%20slotstand%20verwerkt%20en%20maandag%20om%201900%20uur%20zijn%20ze%20zichtbaar%20in%20jouw%20app.' \
          --header 'accept: application/json'
