name: Send Push Messages To All Users

on:
  schedule:
    - cron: '15 19 * * 1' #Every Monday 1915

jobs:
  run-curl-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sending Push Notifications
        run: |
          curl --location 'https://w1ofof2wuh.execute-api.eu-central-1.amazonaws.com/dev/sendpushmessagetoall?title=Jouw%20Portefeuille%20is%20geupdate&body=Al%20jouw%20transacties%20van%20vorige%20week%20zijn%20nu%20verwerkt%20door%20Meesman.' \
          --header 'accept: application/json'
